#!/bin/bash

# Script challenge - Script #1
# 2025 - Brovnik
# With this script you can check IPv4, IPv6, and MAC and copy them to clipboard

show_help(){
    printf "\tWith quip you can check IPv4, IPv6, MAC address, and copy them to the clipboard.\n\n"
    printf "\tquip <options>:\n"
	printf "\t-4 Save IPv4 address to the clipboard.\n"
	printf "\t-6 Save IPv6 address to the clipboard.\n"
	printf "\t-m Save MAC address to the clipboard.\n"
	printf "\t-a Displays all of the above in the terminal.\n"
}

# Source a file that stores, among other things, the host OS
. /etc/os-release
OS=$ID

case "$OS" in
    ubuntu|debian|linuxmint)
    family="debian"
    if ! command -v xclip >/dev/null 2>&1; then
        printf "Missing dependency: xclip\n"
        printf "You can install it with sudo apt install xclip\n"
    exit 1
    fi
    ;;
    almalinux|centos|rhel)
    family="rhel"
    if ! command -v xsel >/dev/null 2>&1; then
        printf "Missing dependency: xsel\n"
        printf "You can install it with sudo dnf install xsel\n"
    exit 2
    fi
    ;;
    arch)
    family="arch"
    if ! command -v xclip >/dev/null 2>&1; then
        printf "Missing dependency: xclip\n"
        printf "You can install it with sudo pacman xclip\n"
    exit 3
    fi
        ;;
    *)
    echo "This script is not supported for your distribution."
    exit 4
esac

# Getting the network interface 
interface=$(ip route get 8.8.8.8 | awk '{print $5}' | head -n1) 
ipv4=$(ip -4 address show "${interface}" | grep inet | awk '{print $2}' | cut -d/ -f1)
ipv6=$(ip -6 address show "${interface}" | grep inet6 | awk '{print $2}' | cut -d/ -f1)
mac=$(ip a s "${interface}" | awk '/link\/ether/ {print $2}')

# Shows help if there is no flag 
[[ $# -eq 0 ]] && { show_help; exit 0; }

while getopts "46ma" opt; do
    case $opt in
    4)  if [ "$family" == "debian" ] || [ "$family" == "arch" ]; then
        printf $ipv4 | xclip -selection clipboard
        fi
        if [ "$family" == "rhel" ]; then
        printf $ipv4 | xsel --clipboard
        fi
        printf "IPv4 copy to clipboard\n";;
    
    6)  if [ "$family" == "debian" ] || [ "$family" == "arch" ]; then
        printf $ipv6 | xclip -selection clipboard
        fi
        if [ "$family" == "rhel" ]; then
        printf $ipv6 | xsel --clipboard
        fi
        printf "IPv6 copy to clipboard\n";;
    
    m)  if [ "$family" == "debian" ] || [ "$family" == "arch" ]; then
        printf $mac | xclip -selection clipboard
        fi
        if [ "$family" == "rhel" ]; then
        printf $mac | xsel --clipboard
        fi
        printf "MAC copied to clipboard\n";; 

    a) show_all="true";;
    
    *) show_help;;
    esac
done

if [[ $show_all == "true" ]]; then
printf "\e[1m\e[32mIPv4: \e[0m${ipv4}\n"
printf "\e[1m\e[33mIPv6: \e[0m${ipv6}\n"
printf "\e[1m\e[34mMAC : \e[0m${mac}\n"
fi
